# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_panel', '0003_auto_20171129_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='task_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_panel.TaskOwner'),
        ),
    ]
