# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_panel', '0004_auto_20171129_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
